Update info

diff --git a/pdf2libre b/pdf2libre
--- a/pdf2libre
+++ b/pdf2libre
@@ -1,71 +1,16 @@
 #!/bin/bash
 
+source $(dirname $0)/pdf2common
+
 VERSION="0.0.1"
-
-INFILE=""
-INPUT=""
-OUTPUT=""
-
 FORMAT='pdf:draw_pdf_Export:{"SelectPdfVersion":{"type":"long","value":"3"}}'
-VALIDATE=false
-MSGOPTS="-dQUIET -sstdout=/dev/null"
-VERAMSGOPTS=""
-DONE_FILE=""
 DIRMADE=false
 UPOLICY="skip"
 DEBUG=false
 
-run() {
-	if $DEBUG; then
-		"$@"
-	else
-		"$@" 2>/dev/null
-	fi
-}
-
-log_good() {
-	[ "$DONE_FILE" != "" ] && echo "$INFILE" >> "$DONE_FILE"
-			
-	echo -e "Processing $INFILE \\t\\t[DONE]"
-}
-
-log_bad() {
-	[ "$BAD_FILE" != "" ] && echo "$INFILE" >> "$BAD_FILE"   
-		
-	echo -e "Processing $INFILE \\t\\t[INVALID]"
-}
-
-log_pass() {
-	[ "$PASS_FILE" != "" ] && echo "$INFILE" >> "$PASS_FILE"   
-		
-	echo -e "Processing $INFILE \\t\\t[FAIL]"
-}
-
-do_finalize() {
-	if [ $1 -eq 0 ]; then
-
-		if [ "$VALIDATE" != "" ]; then
-			
-			eval "$VALIDATE" --extract --flavour 3b --format text "$2" >/dev/null
-			
-			if [ $? -eq 0 ]; then
-				log_good
-			else
-				log_bad
-			fi
-		
-		else
-			log_good
-		fi
-		
-	else
-		if $DIRMADE; then
-			rm -d $(dirname "${OUTPUT}")
-		fi
-
-		log_pass
-	fi
-}
+INFILE=""
+INPUT=""
+OUTPUT=""
 
 if [ "$1" == "" ]; then
 	exit
@@ -74,9 +19,6 @@ while [ "$1" != "" ]; do
 	PARAM=`echo $1 | awk -F= '{print $1}'`
 	VALUE=`echo $1 | awk -F= '{print $2}'`
 	case $PARAM in
-		-h | --help)
-			exit
-			;;
 		-v | --version)
 			echo $VERSION
 			exit
@@ -128,12 +70,12 @@ while [ "$1" != "" ]; do
 			elif [ "$OUTPUT" == "" ]; then
 				OUTPUT=$PARAM
 			else
-				echo "  ERROR: too many PDF files as input!"
+				echo "ERROR: too many PDF files as input!"
 				exit 1
 			fi
 			;;
 		*)
-			echo "  ERROR: unknown parameter \"$PARAM\""
+			echo "ERROR: unknown parameter \"$PARAM\""
 			exit 1
 			;;
 	esac
@@ -151,15 +93,15 @@ if [ "$OUTPUT" == "" ]; then
 fi
 
 if [ ! -f "$INPUT" ]; then
-		
+
 	log_pass
 	exit 1
 
 fi
 
 if [ -f "$OUTPUT" ]; then
-		
-	[ "$UPOLICY" == "skip" ] && exit 0	
+
+	[ "$UPOLICY" == "skip" ] && exit 0
 	[ "$UPOLICY" == "overwrite" ] && rm "$OUTPUT"
 
 fi
@@ -176,9 +118,9 @@ if $DEBUG; then
 	echo "  DEBUG: PDF creator '$PDFCREATOR'"
 fi
 
-if [ ! -d "$OUTDIR" ]; then 
+if [ ! -d "$OUTDIR" ]; then
 	mkdir -p "$OUTDIR" && DIRMADE=true
-	
+
 	if [ $? != 0 ]; then
 		log_bad
 		exit 1
@@ -206,6 +148,5 @@ run exiftool -overwrite_original \
 if [ "$TMPOUT" != "$OUTPUT" ]; then
 	mv "$TMPOUT" "$OUTPUT"
 fi
-	
-do_finalize $? "$TMPOUTPUT"
 
+do_finalize $? "$TMPOUTPUT"
diff --git a/pdf2mark b/pdf2mark
--- a/pdf2mark
+++ b/pdf2mark
@@ -1,8 +1,6 @@
 #!/bin/bash
 
-INPUT=$1
-WATERMARK=$2
-OUTPUT=$3
+source $(dirname $0)/pdf2common
 
 PSFILE=$(mktemp -p /dev/shm/ XXXXXXXXXX.tmp)
 TMPFILE=$(mktemp -p /dev/shm/ XXXXXXXXXX.tmp)
@@ -10,9 +8,79 @@ TMPFILE=$(mktemp -p /dev/shm/ XXXXXXXXXX.tmp)
 OUTDIR=$(dirname "${OUTPUT}")
 INFILE=$(basename "${INPUT}")
 
-[ "$INPUT" == "" ] && exit 1
-[ "$WATERMARK" == "" ] && exit 2
-[ "$OUTPUT" == "" ] && OUTPUT="$OUTDIR/marked_$INFILE"
+if [ "$1" == "" ]; then
+	exit
+fi
+while [ "$1" != "" ]; do
+	PARAM=`echo $1 | awk -F= '{print $1}'`
+	VALUE=`echo $1 | awk -F= '{print $2}'`
+	case $PARAM in
+		-v | --version)
+			echo $VERSION
+			exit
+			;;
+		--debug)
+			DEBUG=true
+			MSGOPTS=""
+			;;
+		--good)
+			DONE_FILE=$VALUE
+			;;
+		--bad)
+			BAD_FILE=$VALUE
+			;;
+		--pass)
+			PASS_FILE=$VALUE
+			;;
+		--validate)
+			VALIDATE=$VALUE
+			;;
+		--mark)
+			WATERMARK=$VALUE
+			;;
+		*.pdf)
+			if [ "$INPUT" == "" ]; then
+				INPUT=$PARAM
+			else
+				echo "ERROR: too many PDF files as input!"
+				exit 1
+			fi
+			;;
+		*)
+			echo "ERROR: unknown parameter \"$PARAM\""
+			exit 1
+			;;
+	esac
+	shift
+done
+
+OUTDIR=$(dirname "${OUTPUT}")
+INFILE=$(basename "${INPUT}")
+
+if [ "$WATERMARK" == "" ]; then
+
+	exit 1
+
+fi
+
+if [ ! -f "$INPUT" ]; then
+
+	log_pass
+	exit 1
+
+fi
+
+if [ ! -d "$OUTDIR" ]; then
+	mkdir -p "$OUTDIR" && DIRMADE=true
+
+	if [ $? != 0 ]; then
+		log_bad
+
+		rm "$PSFILE"
+		rm "$TMPFILE"
+		exit 1
+	fi
+fi
 
 echo "%% Watermark ps file
 /watermarkText { ($WATERMARK) } def
@@ -33,17 +101,17 @@ echo "%% Watermark ps file
 			watermarkFont
 			watermarkColor
 			watermarkAlpha
-			
+
 			pageWidth pageHeight translate
 			0 0 moveto
 			watermarkText false charpath flattenpath pathbbox
 			4 2 roll pop pop
 			-5 -5 moveto
-			
+
 			watermarkAngle rotate
 			-1 mul exch -1 mul exch
 			rmoveto
-			
+
 			watermarkText show
 
 			grestore
@@ -52,8 +120,12 @@ echo "%% Watermark ps file
 	} bind
 >> setpagedevice" >> "$PSFILE"
 
-gs -dBATCH -dNOPAUSE -dALLOWPSTRANSPARENCY -q -sDEVICE=pdfwrite -sOutputFile="$TMPFILE" "$PSFILE" "$INPUT"
-
+run gs $MSGOPTS \
+	-dBATCH -dNOPAUSE -dALLOWPSTRANSPARENCY -sDEVICE=pdfwrite
+	-sOutputFile="$TMPFILE" "$PSFILE" "$INPUT" && \
 cp "$TMPFILE" "$OUTPUT"
+
+do_finalize $? "$TMPFILE"
+
 rm "$PSFILE"
 rm "$TMPFILE"
diff --git a/pdf2meta b/pdf2meta
--- a/pdf2meta
+++ b/pdf2meta
@@ -1,17 +1,11 @@
 #!/bin/bash
 
+source $(dirname $0)/pdf2common
+
 VERSION="0.0.1"
 INFILE=""
 INPUT=""
 DEBUG=false
-
-run() {
-	if $DEBUG; then
-		"$@"
-	else
-		"$@" 2>/dev/null
-	fi
-}
 
 #=====# INPUT PARSER #=====#
 if [ "$1" == "" ]; then
@@ -21,9 +15,6 @@ while [ "$1" != "" ]; do
 	PARAM=`echo $1 | awk -F= '{print $1}'`
 	VALUE=`echo $1 | awk -F= '{print $2}'`
 	case $PARAM in
-		-h | --help)
-			exit
-			;;
 		-v | --version)
 			echo $VERSION
 			exit
@@ -31,6 +22,9 @@ while [ "$1" != "" ]; do
 		--debug)
 			DEBUG=true
 			MSGOPTS=""
+			;;
+		--validate)
+			VALIDATE=$VALUE
 			;;
 		--cleanmetadata)
 			PDFTITLE=""
@@ -57,22 +51,29 @@ while [ "$1" != "" ]; do
 		*.pdf)
 			if [ "$INPUT" == "" ]; then
 				INPUT=$PARAM
-				INFILE=$(basename "${PARAM}")
 			else
-				echo "  ERROR: too many PDF files as input!"
+				echo "ERROR: too many PDF files as input!"
 				exit 1
 			fi
 			;;
 		*)
-			echo "  ERROR: unknown parameter \"$PARAM\""
+			echo "ERROR: unknown parameter \"$PARAM\""
 			exit 1
 			;;
 	esac
 	shift
 done
 
+INFILE=$(basename "${INPUT}")
 
-[ -f "$INPUT" ] && run exiftool -overwrite_original \
+if [ ! -f "$INPUT" ]; then
+
+	log_pass
+	exit 1
+
+fi
+
+run exiftool -overwrite_original \
 	-AllDates=now \
 	-Title="$PDFTITLE" \
 	-Producer="$PDFCREATOR" \
@@ -84,4 +85,6 @@ done
 	-xmp:Description="$PDFSUBJECT" \
 	-xmp:Creator="$PDFAUTHOR" \
 	-xmp:CreatorTool="$PDFCREATOR" \
-	-q "$INPUT" && echo -e "Updated $INFILE \\t\\t[DONE]"
+	-q "$INPUT"
+
+do_finalize $? "$TMPOUTPUT"
